name: trivia
description: A trivia project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  html: ^0.15.0
  flutter_svg: ^1.1.0
  http: ^0.13.3
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  lottie: ^1.0.1
  path: ^1.8.0
  provider: ^6.0.3
  settings_ui: ^2.0.2
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+3
  google_fonts: ^3.0.1
  dio: ^4.0.6
  bubble: ^1.2.1
  step_progress_indicator: ^1.0.2
  fl_chart: ^0.55.0
  flutter_spinkit: ^5.1.0
  connectivity_plus: ^2.3.6
  overlay_support: ^2.0.1
  internet_connection_checker: ^0.0.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.2.4

flutter_native_splash:
  color: "#3F51B5"
  image: assets/images/auth/home_banner.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher/launcher.png"
  adaptive_icon_background: "assets/launcher/launcher_adaptive_back.png"
  adaptive_icon_foreground: "assets/launcher/launcher_adaptive_fore.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/auth/
    - assets/images/category/
    - assets/animations/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu-Light.ttf
          weight: 200
        - asset: assets/fonts/Ubuntu-Italic.ttf
          style: italic
        - asset: assets/fonts/Ubuntu-LightItalic.ttf
          weight: 200
          style: italic
